export const CMT_VISITED_LIST = 'CMT_VISITED_LIST';
export const CMT_POSITION_PROVINCE = 'CMT_POSITION_PROVINCE';
export const CMT_POSITION_CITY = 'CMT_POSITION_CITY';
export const CMT_USER = 'CMT_USER';